config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get    '/signup',  		     to: 'users#new'
  post   '/signup',  		     to: 'users#create'
  get     '/login', 	       to: 'sessions#new'
  post    '/login', 	       to: 'sessions#create'
  delete '/logout',  		     to: 'sessions#destroy'
  post   '/users_from_file', to: 'users#create_csv'


  # resources :project
  
  resources :users do
    resources :reimbursements
    resources :allowances
    resources :dope_adjustments
    resources :nope_adjustments
    resources :payslips do
      member do
        post :toggle_paid
        post :toggle_pay_all
        post :toggle_unpay_all
        get  :sss_bracket
        get  :philhealth_bracket
        get  :pagibig_bracket
        get  :withholding_bracket
      end
    end
  end

  resources :payrolls


  # , only: [:edit, :delete, :create, :update, :destroy, :new, :index]

  # resources :reimbursements

end

app/controllers/payslips_controller.rb
class PayslipsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @payslips = Payslip.all
  end
  
  def toggle_paid
    @payslips = Payslip.find(params[:id])

    @payslips.toggle(:paid)
    @payslips.save  
    flash[:success] = "Payslip updated!"
    if params[:payroll_id] 
      redirect_to payroll_path(params[:payroll_id])
    else
      redirect_to payrolls_path 
    end
  end

 def toggle_pay_all
    @payroll = Payroll.find(params[:id])

    @payroll.payslips.each do |payslip|
      payslip.update_attributes({paid: "true"})
    end
    flash[:success] = "All payslips are paid!"
    redirect_to payroll_path
  end

  def toggle_unpay_all
    @payroll = Payroll.find(params[:id])

    @payroll.payslips.each do |payslip|
      payslip.update_attributes({paid: "false"})
    end
    flash[:success] = "All payslips are not yet paid!"
    redirect_to payroll_path
  end

  def sss_bracket

  end

  def philhealth_bracket

  end

  def pagibig_bracket

  end

  def withholding_bracket
    
  end


  def show
    
    @reimbursements = Reimbursement.all
    @payslips = Payslip.find(params[:id])

    @status = @payslips.employee.no_of_dependents

    @dependents = @payslips.employee.status

    #cutoff
    @salary = @payslips.employee.base_salary/2

    #sss computation
    @payslips.sss = sssBracket(@salary)*0.0363
    # @payslips.sss = @payslips.monthly_salary_sss*0.0363
    # @employer_sss = @payslips.monthly_salary_sss*0.0737

    #philhealth_computation
    @monthly_salary_philhealth = philBracket(@salary)
    @payslips.philhealth = @monthly_salary_philhealth/40
    @employer_philhealth = @payslips.philhealth/2

    #pagibig_computation
    @monthly_salary_pagibig = pagibigBracket(@salary)
    @payslips.pagibig    = @monthly_salary_pagibig
    @employer_philhealth = @monthly_salary_pagibig

    #withholding_tax computation
    @monthly_withholding_tax = withholding_tax(@salary, @status, @dependents)
    @withholding_tax = @monthly_withholding_tax

    #total reimbursements computation
    @total_reimbursements = 0

    @payslips.employee.reimbursements.each do |reimbursement|
      @total_reimbursements += reimbursement.amount
    end

    #total reimbursements computation
    @total_allowances = 0

    @payslips.employee.allowances.each do |allowance|
      @total_allowances += allowance.amount
    end
    
    #total less adjustments
    @total_nope_adjustments = 0

    @payslips.employee.nope_adjustments.each do |nope_adjustment|
      @total_nope_adjustments += nope_adjustment.amount
    end

    #total plus adjustments
    @total_dope_adjustments = 0

    @payslips.employee.dope_adjustments.each do |dope_adjustment|
      @total_dope_adjustments += dope_adjustment.amount
    end

    #final_pay computation
    @final_pay = (@payslips.employee.base_salary + @total_allowances + @total_reimbursements + @total_dope_adjustments) - (@payslips.sss + @payslips.pagibig + @payslips.philhealth + @withholding_tax + @total_dope_adjustments )
 
    
  end

  def new
    @payslip = Payslip.new
  end

  def create
  end

  def destroy
  end

  def edit
    @payslips = Payslip.find(params[:id])
  end

  def update
  end

  private 

  def payroll_params
    params.require(:payroll).permit(:start_period, :end_period)
  end
  
  def payslip_params
    params.require(:payslip).permit(:base_salary, :sss, :pagibig, 
                                                :philhealth, :paid, :avatar)
  end
  

  def sssBracket(salary)
    thousands = salary / 1000
    hundreds  = salary % 1000
    percent   = hundreds / 1000.0

    if   percent < 0.25
     thousands = thousands * 1000
    elsif percent < 0.75
     thousands = (thousands * 1000) + 500
    elsif thousands >= 15
     thousands = thousands = 16000
    else 
     thousands = (thousands + 1) * 1000
    end

    return thousands
  end
  

  def philBracket (salary)
      salary = salary/1000
      if salary <= 7
        salary = 7000
      elsif salary >= 35
        salary = 35000
      else
        return salary * 1000
      end 
  end

  def pagibigBracket (salary)
      if salary <= 1500
        salary = salary*0.01
      else
        salary = salary*0.02
        if salary >= 100
          return salary = 100
        end
      end
  end

  def withholding_tax(salary, status, dependents)

      if status = "Single" || status = "Married"

        if dependents = 0
            if salary < 2083
              return salary = 2083
            elsif salary >= 2083 && salary < 2500
              salary = salary-2083
              salary = salary*0.05
            elsif salary >= 2500 && salary < 3333
              salary = salary-2500
              salary = salary*0.10+(20.83)
            elsif salary >= 3333 && salary < 5000
              salary = salary-3333
              salary = salary*0.15+(104.17)
            elsif salary >= 5000 && salary < 7917
              salary = salary-5000
              salary = salary*0.20+(354.17)
            elsif salary >= 7917 && salary < 12500
              salary = salary-7917
              salary = salary*0.25+(937.50)
            elsif salary >= 12500 && salary < 22917
              salary = salary-12500
              salary = salary*0.30+(2083.33)
            elsif salary > 22917
              salary = salary-22917
              salary = salary*0.32+(5208.33)
            end

        elsif dependents = 1
            if salary < 3125
              return salary = 3125
            elsif salary >= 3125 && salary < 3542
              salary = salary-3125
              salary = salary*0.05
            elsif salary >= 3542 && salary < 4375
              salary = salary-3542
              salary = salary*0.10+(20.83)
            elsif salary >= 4375 && salary < 6042
              salary = salary-4375
              salary = salary*0.15+(104.17)
            elsif salary >= 6042 && salary < 8958
              salary = salary-6042
              salary = salary*0.20+(354.17)
            elsif salary >= 8958 && salary < 13542
              salary = salary-8958
              salary = salary*0.25+(937.50)
            elsif salary >= 13542 && salary < 23958
              salary = salary-13542
              salary = salary*0.30+(2083.33)
            elsif salary > 23958
              salary = salary-23958
              salary = salary*0.32+(5208.33)
            end

        elsif dependents = 2
            if salary < 4167
              return salary = 4167
            elsif salary >= 4167 && salary < 4583
              salary = salary-4167
              salary = salary*0.05
            elsif salary >= 4583 && salary < 5417
              salary = salary-4583
              salary = salary*0.10+(20.83)
            elsif salary >= 5417 && salary < 7083
              salary = salary-5417
              salary = salary*0.15+(104.17)
            elsif salary >= 7083 && salary < 10000
              salary = salary-7083
              salary = salary*0.20+(354.17)
            elsif salary >= 10000 && salary < 14583
              salary = salary-10000
              salary = salary*0.25+(937.50)
            elsif salary >= 14583 && salary < 25000
              salary = salary-14583
              salary = salary*0.30+(2083.33)
            elsif salary > 25000
              salary = salary-25000
              salary = salary*0.32+(5208.33)
            end

        elsif dependents = 3
            if salary < 5208
              return salary = 5208
            elsif salary >= 5208 && salary < 5625
              salary = salary-5208
              salary = salary*0.05
            elsif salary >= 5625 && salary < 6458
              salary = salary-5625
              salary = salary*0.10+(20.83)
            elsif salary >= 6458 && salary < 8125
              salary = salary-6458
              salary = salary*0.15+(104.17)
            elsif salary >= 8125 && salary < 11042
              salary = salary-8125
              salary = salary*0.20+(354.17)
            elsif salary >= 11042 && salary < 15625
              salary = salary-11042
              salary = salary*0.25+(937.50)
            elsif salary >= 15625 && salary < 26042
              salary = salary-15625
              salary = salary*0.30+(2083.33)
            elsif salary > 26042
              salary = salary-26042
              salary = salary*0.32+(5208.33)
            end

        elsif dependents >= 4
            if salary < 6250
              return salary = 6250
            elsif salary >= 6250 && salary < 6667
              salary = salary-6250
              salary = salary*0.05
            elsif salary >= 6667 && salary < 7500
              salary = salary-6667
              salary = salary*0.10+(20.83)
            elsif salary >= 7500 && salary < 9167
              salary = salary-7500
              salary = salary*0.15+(104.17)
            elsif salary >= 9167 && salary < 12083
              salary = salary-9167
              salary = salary*0.20+(354.17)
            elsif salary >= 12083 && salary < 16667
              salary = salary-12083
              salary = salary*0.25+(937.50)
            elsif salary >= 16667 && salary < 27083
              salary = salary-16667
              salary = salary*0.30+(2083.33)
            elsif salary > 27083
              salary = salary-27083
              salary = salary*0.32+(5208.33)
            end
        end

      else
        return salary = 1000000
      end

  end
end

app/helpers/payslips_helper.rb
module PayslipsHelper
end

app/views/payslips/_payslip.html.erb
<h1>Payslips(<%= @payslips.id %>)</h1>
<h3>  

  

  <div>

    <div class="Employee_data"> Employee name </div>
      <div class="Employee_name">
      <%= @payslips.employee.name %><br/>
      <% if @payslips.employee.no_of_dependents = 0 %>
      <%= @payslips.employee.status %>, No Dependents 
      <% else %>
      <%= @payslips.employee.no_of_dependents %>, dependent(s)
      <% end %>
      </div>
      
      <table class="table_payslip" >
       <thead>
         <tr>
           <th>Payslip period</th>
           <th>&nbsp;</th>
           <th>&nbsp;</th>
           <th><%= @payslips.payroll.start_period %> to <%= @payslips.payroll.end_period %></th>
         </tr>

         <tr>
           <th>Base Salary</th>
           <th>&nbsp;</th>
           <th><%= number_to_currency payslip.base_salary, unit: "PHP " %></th>
           <th>&nbsp;</th>
         </tr>

         <tr>
           <th>  <%= link_to "SSS", sss_bracket_user_payslip_url %> </th>

           <th>&nbsp;</th>
           <th>&nbsp;</th>
           <th><%= number_to_currency payslip.sss, unit: "PHP " %></th>
         </tr>

         <tr>
           <th> <%= link_to "Pag-ibig", pagibig_bracket_user_payslip_url %> </th>
           <th>&nbsp;</th>
           <th>&nbsp;</th>
           <th><%= number_to_currency payslip.pagibig, unit: "PHP " %></th>
         </tr>
         
         <tr>
           <th> <%= link_to "Philhealth", philhealth_bracket_user_payslip_url %> </th>
           <th>&nbsp;</th>
           <th>&nbsp;</th>
           <th><%= number_to_currency payslip.philhealth, unit: "PHP " %></th>
         </tr>
         
         <tr>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
         </tr>

         <tr >
           <th>Allowances</th>
           <% @payslips.employee.allowances.each do |allowance| %> 
            <% if @payslips.employee.allowances.count > 1 %>
             <tr>
             <th>Description: </th>
             <th><%= allowance.description %> <br/></th>
             <th><%= number_to_currency allowance.amount, unit: "PHP " %> <br /></th>
             <th> &nbsp; </th>
             </tr>
            <% else %>
            <tr>
             <th>Description: </th>
             <th><%= allowance.description %> <br/></th>
             <th><%= number_to_currency allowance.amount, unit: "PHP " %> <br /></th>
             <th> &nbsp; </th></tr> <% end %>
            <% end %>
         </tr>

        <% if !@payslips.paid? %>
            <th>&nbsp;</th>
            <th> <%= link_to "Add new allowance?", new_user_allowance_path %></th>
            <th> &nbsp; </th>
            <th> &nbsp; </th>
        <% end %>
            

         <tr>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
         </tr>

         <tr>
           <th>Reimbursements</th>
           <% @payslips.employee.reimbursements.each do |reimbursement| %> 
              <% if @payslips.employee.reimbursements.count > 1 %>
                 <tr>
                 <th>Category: </th>
                 <th><%= reimbursement.category %> <br/></th>
                 <th><%= number_to_currency reimbursement.amount, unit: "PHP " %> <br /></th>
                 <th> &nbsp; </th>
                 </tr>
              <% else %>
                <tr>
                   <th>Category: </th>
                   <th><%= reimbursement.category %> <br/></th>
                   <th><%= number_to_currency reimbursement.amount, unit: "PHP " %> <br /></th>
                   <th> &nbsp; </th>
                 </tr> 
              <% end %>
            <% end %>

        <% if !@payslips.paid? %>
            
            <th> <%= link_to "Add new reimbursement?", new_user_reimbursement_path %> </th>
            <th> &nbsp; </th>
            <th> &nbsp; </th>
         </tr> 

        <% end %>
           

         <tr>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
         </tr>

          <tr>
           <th><%= link_to "Withholding tax", withholding_bracket_user_payslip_url %></th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th><%= number_to_currency @withholding_tax, unit: "PHP " %></th>
         </tr>


         <tr>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
         </tr>


         <tr>
           <th>Adjustments (Less)</th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <% @payslips.employee.nope_adjustments.each do |nope_adjustment| %> 
            <% if @payslips.employee.nope_adjustments.count > 1 %>
             <tr>
             <th>Description: </th>
             <th><%= nope_adjustment.description %> <br/></th>
             <th> &nbsp; </th>
             <th><%= number_to_currency nope_adjustment.amount, unit: "PHP " %> <br />
             </th>
             </tr>
            <% else %>
            <tr>
             <th>Description: </th>
             <th><%= nope_adjustment.description %> <br/></th>
             <th> &nbsp; </th>
             <th><%= number_to_currency nope_adjustment.amount, unit: "PHP " %> <br /></th>
             </tr> <% end %>
            <% end %>
         </tr>

        <% if !@payslips.paid? %>
            <th> &nbsp;</th>
            <th> <%= link_to "Add new adjustment (less)?", new_user_nope_adjustment_path %></th>
            <th> &nbsp; </th>
            <th> &nbsp; </th>
        <% end %>
         
         <tr>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
         </tr>

         <tr>
           <th>Adjustments (Plus)</th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <% @payslips.employee.dope_adjustments.each do |dope_adjustment| %> 
            <% if @payslips.employee.dope_adjustments.count > 1 %>
             <tr>
             <th>Description: </th>
             <th><%= dope_adjustment.description %> <br/></th>
             <th> &nbsp; </th>
             <th><%= number_to_currency dope_adjustment.amount, unit: "PHP " %> <br />
             </th>
             </tr>
            <% else %>
            <tr>
             <th>Description: </th>
             <th><%= dope_adjustment.description %> <br/></th>
             <th> &nbsp; </th>
             <th><%= number_to_currency dope_adjustment.amount, unit: "PHP " %> <br /></th>
             </tr> <% end %>
            <% end %>
         </tr>

         <% if !@payslips.paid? %>
            <th> &nbsp;</th>
            <th> <%= link_to "Add new adjustment (plus)?", new_user_dope_adjustment_path %> </th>
            <th> &nbsp; </th>
            <th> &nbsp; </th>
         <% end %>

         <tr>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
         </tr>

         <tr class="Final">
           <th >Final</th>
           <th> &nbsp; </th>
           <th> &nbsp; </th>
           <th><%= number_to_currency @final_pay, unit: "PHP " %></th>
         </tr>

        

         
       </thead>
        
      </table>
      
    </div>
    
  </div>



</h3>

app/views/payslips/edit.html.erb
<h1> edit Payslips </h1>

app/views/payslips/index.html.erb
<h1>Payslips</h1>

<div class="Employee_name">
<h3>Employee_name</h3>
</div>
<div class="Employee_name">
      <%=  @user.name %><br/>
      <% if  @user.no_of_dependents = 0 %>
      <%=  @user.status %>, No Dependents 
      <% else %>
      <%=  @user.no_of_dependents %>, dependent(s)
      <% end %>
</div>


<h3> Check payslips:
<% @user.payslips.each do |payslip| %>
</br></br>
<%= link_to "Payslip No: #{payslip.id}", user_payslip_path(@user.id, payslip.id) %>
<% end %>
</h3>

app/views/payslips/new.html.erb
<h1> New Payslip </h1>

app/views/payslips/pagibig_bracket.erb
<h1> Pagibig Bracket </h1>

<div class="pagibig_bracket" >
<%= image_tag 'pagibig_bracket.png', width: 500, height: 300 %>
</div>

<div class="back" >
<%= link_to "Go back", user_payslip_path %>
</div>

app/views/payslips/philhealth_bracket.erb
<h1> Philhealth Bracket </h1>

<div class="philhealth_bracket" >
<%= image_tag 'philhealth_bracket.png', width: 900, height: 900 %>
</div>

<div class="back" >
<%= link_to "Go back", user_payslip_path %>
</div>

app/views/payslips/show.html.erb
<%= render @payslips %>

app/views/payslips/sss_bracket.erb
<h1> SSS Bracket </h1>

<div class="sss_bracket" >
<%= image_tag 'sss_bracket.jpg', width: 900, height: 700 %>
</div>

<div class="back" >
<%= link_to "Go back", user_payslip_path %>
</div>

app/views/payslips/withholding_bracket.erb
<h1> Withholding Tax Bracket </h1>

<div class="withholding_bracket" >
<%= image_tag 'withholding_tax.png', width: 600, height: 500 %>
</div>

<div class="back" >
<%= link_to "Go back", user_payslip_path %>
</div>