config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get    '/signup',  		     to: 'users#new'
  post   '/signup',  		     to: 'users#create'
  get     '/login', 	       to: 'sessions#new'
  post    '/login', 	       to: 'sessions#create'
  delete '/logout',  		     to: 'sessions#destroy'
  post   '/users_from_file', to: 'users#create_csv'


  # resources :project
  
  resources :users do
    resources :reimbursements
    resources :allowances
    resources :dope_adjustments
    resources :nope_adjustments
    resources :payslips do
      member do
        post :toggle_paid
        post :toggle_pay_all
        post :toggle_unpay_all
        get  :sss_bracket
        get  :philhealth_bracket
        get  :pagibig_bracket
        get  :withholding_bracket
      end
    end
  end

  resources :payrolls


  # , only: [:edit, :delete, :create, :update, :destroy, :new, :index]

  # resources :reimbursements

end

app/models/nope_adjustment.rb
class NopeAdjustment < ApplicationRecord
  # belongs_to :user
  belongs_to :user
  validates :user_id, presence: true
  validates :description, presence: true, length: { maximum: 140 }
  validates :amount, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/controllers/nope_adjustments_controller.rb
class NopeAdjustmentsController < ApplicationController

	def index
		  # render html: "hello, world!"
	   @user = User.find(params[:user_id])
	 	if logged_in? && current_user.admin?
	  		@nope_adjustments = NopeAdjustment.paginate(page: params[:page])
		else
			@nope_adjustments = @user.nope_adjustments.all.paginate(page: params[:page])
		end
	end

	def show
		# render html: "hello, world!"
	   @user = User.find(params[:user_id])
	   @nope_adjustments = NopeAdjustment.find(params[:id])
	end


   def edit
   	@user = User.find(params[:user_id])
    @nope_adjustment = NopeAdjustment.find(params[:id])
   end

   def update
   	@user = User.find(params[:user_id])
    @nope_adjustment = NopeAdjustment.find(params[:id])
    if @nope_adjustment.update_attributes(nope_adjustments_params)
      flash[:success] = "Adjustment updated"
      redirect_to user_nope_adjustments_path
    else
      render 'edit'
    end
   end

   def destroy
   	@user = User.find(params[:user_id])
    @nope_adjustment = @user.nope_adjustments.find(params[:id])
    @nope_adjustment.destroy
    flash[:success] = "Adjustment deleted"
    redirect_to user_nope_adjustments_path
   end

   def create
  	@user = User.find(params[:user_id])
  	@nope_adjustments = @user.nope_adjustments.new(nope_adjustments_params)
    if @nope_adjustments.save
      flash[:success] = "-Adjustment successfully created."
      redirect_to user_nope_adjustments_path
      # Handle a successful save.
    else
      render 'new'
    end
   end

   def new
   	@user = User.find(params[:user_id])
   	# @nope_adjustments = @user.nope_adjustments 
   end
   
   def correct_user
      @nope_adjustments = current_user.nope_adjustments.find_by(id: params[:id])
      redirect_to user_path if @nope_adjustments.nil?
   end

   private
    def nope_adjustments_params
      params.require(:nope_adjustment).permit(:description, :amount)
    end

end

app/helpers/nope_adjustments_helper.rb
module NopeAdjustmentsHelper
end

app/views/nope_adjustments/_nope_adjustment.html.erb
<li id="nope_adjustment-<%= nope_adjustment.id %>">
  
  <span class="user"><%= link_to nope_adjustment.user.name, nope_adjustment.user %></span>
  <span class="description"><h4>Description:</h4><%= nope_adjustment.description %></span>
  <span class="amount"><h4>Amount:</h4>₱<%= nope_adjustment.amount %></span>


    <% if current_user?(nope_adjustment.user) || logged_in? && current_user.admin? %>
     <br>
      <%= link_to "Add", new_user_nope_adjustment_path(id: nope_adjustment.id,nope_adjustment: nope_adjustment), data: { confirm: "Add new -Adjustment?" } %>

       <% if logged_in? && current_user.admin? %>
        |
        <%= link_to "Edit", edit_user_nope_adjustment_path(id: nope_adjustment.id, nope_adjustment: nope_adjustment), data: { confirm: "Edit Adjustments?" } %>
        | 
        <%= link_to "Delete", user_nope_adjustment_path(id: nope_adjustment.id, nope_adjustment: nope_adjustment), method: :delete,
                                      data: { confirm: "Delete Adjustments" } %>
       <% end %>

    <% end %>

  <span class="timestamp">
    Posted  <%= time_ago_in_words(nope_adjustment.created_at) %> ago.


  </span>
  



</li>

app/views/nope_adjustments/edit.html.erb
<% provide(:title, "Edit user adjustment") %>
<h1>Edit your adjustment</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for [@user, @nope_adjustment] do |f| %>
      <%= render 'shared/error_messages' %>


      <%= f.label :description %>
      <%= f.text_area :description, placeholder: "Please input description.", class: 'form-control' %>
      

      <%= f.label :amount, "Amount" %>
      <%= f.text_field :amount, class: 'form-control' %>

      
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    
  </div>
</div>

app/views/nope_adjustments/index.html.erb
<% provide(:title, @user.username) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>



    <div class="col-md-8">
    
            
            <h1> -Adjustments </h1>
            <h3><%= link_to "-Add new adjustments?", new_user_nope_adjustment_path %></h3>
            <% if @user.nope_adjustments.any? || @user.admin? %>
            
            <ol class="nope_adjustments">
            <%= render @nope_adjustments %>
            </ol>
            <%= will_paginate @nope_adjustments %>
            <% else %>
            
            
            <% end %>


    </div>

    
</div>

app/views/nope_adjustments/new.html.erb
<% provide(:title, "Add new adjustment") %>
<h1>Add new adjustment</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(NopeAdjustment.new, url: user_nope_adjustments_path) do |f| %>
      <%= render 'shared/error_messages' %>

     
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :amount, "Amount" %>
      <%= f.text_field :amount, class: 'form-control' %>

      
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    
  </div>
</div>

app/views/nope_adjustments/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>



    <div class="col-md-8">
    
            <% if @user.nope_adjustments.any? %>
            <h1> +Adjustments </h1>
            <ol class="nope_adjustments">
            <%= render @nope_adjustments %>
            </ol>
            <% end %>
            

    </div>

    
</div>