config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get    '/signup',  		     to: 'users#new'
  post   '/signup',  		     to: 'users#create'
  get     '/login', 	       to: 'sessions#new'
  post    '/login', 	       to: 'sessions#create'
  delete '/logout',  		     to: 'sessions#destroy'
  post   '/users_from_file', to: 'users#create_csv'


  # resources :project
  
  resources :users do
    resources :reimbursements
    resources :allowances
    resources :dope_adjustments
    resources :nope_adjustments
    resources :payslips do
      member do
        post :toggle_paid
        post :toggle_pay_all
        post :toggle_unpay_all
        get  :sss_bracket
        get  :philhealth_bracket
        get  :pagibig_bracket
        get  :withholding_bracket
      end
    end
  end

  resources :payrolls


  # , only: [:edit, :delete, :create, :update, :destroy, :new, :index]

  # resources :reimbursements

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Payroll</a>
    by <a href="http://www.michaelhartl.com/">Ryan Jay Dayrit</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Intelimina", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>

          <% if logged_in? && current_user.admin? %>
          <li><%= link_to "New Account", signup_path %></li>
          <li><%= link_to "Employees", users_path %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Reimbursements <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Reimbursements", user_reimbursements_path(current_user) %></li>
              <li><%= link_to "Allowances", user_allowances_path(current_user) %></li>
              <li><%= link_to "+ Adjustments", user_dope_adjustments_path(current_user) %></li>
              <li><%= link_to "- Adjustments", user_nope_adjustments_path(current_user) %></li>
              
            </ul>
          </li>

          
          <li><%= link_to "Payrolls", payrolls_path if current_user.admin? %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
          

          <% elsif logged_in? && !current_user.admin? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Reimbursements <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Reimbursements", user_reimbursements_path(current_user) %></li>
              <li><%= link_to "Allowances", user_allowances_path(current_user) %></li>
              <li><%= link_to "+ Adjustments", user_dope_adjustments_path(current_user) %></li>
              <li><%= link_to "- Adjustments", user_nope_adjustments_path(current_user) %></li>
              
            </ul>
          </li>

          <li><%= link_to "Payslips", user_payslips_path(current_user) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>

        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>      
    </div>
  </body>
</html>